################################################################################
# program_fpga.tcl
# Vivado Hardware Manager script to program a bitstream onto:
#   FPGA Part : xc7a35tftg256-1
#   Board     : Edge Artix-7 (Arty A7-35T class board)
#
# Usage:
#   vivado -mode batch -source program_fpga.tcl
#
# Assumes:
#   - The board is connected via USB-JTAG (e.g. on-board FTDI/Digilent JTAG-HS)
#   - The bitstream was already generated by build_vivado.tcl at:
#       ./build/top_adder_subtractor.bit
#
# Edit BIT_FILE below if your bitstream lives somewhere else.
################################################################################

set BIT_FILE   "./build/top_adder_subtractor.bit"
set TARGET_PART "xc7a35t"

# ------------------------------------------------------------------------
# 1. Sanity check
# ------------------------------------------------------------------------
if {![file exists $BIT_FILE]} {
    puts "ERROR: Bitstream not found at: $BIT_FILE"
    puts "ERROR: Run build_vivado.tcl first to generate the bitstream."
    exit 1
}

# ------------------------------------------------------------------------
# 2. Connect to the local hardware server / cable
# ------------------------------------------------------------------------
puts "INFO: Opening hardware manager..."
open_hw_manager

puts "INFO: Connecting to hw_server (localhost)..."
connect_hw_server -allow_non_jtag

puts "INFO: Opening hardware target..."
open_hw_target

# ------------------------------------------------------------------------
# 3. Locate the target device on the JTAG chain
# ------------------------------------------------------------------------
set hw_devices [get_hw_devices]
puts "INFO: Devices found on JTAG chain: $hw_devices"

set hw_device ""
foreach dev $hw_devices {
    if {[string match -nocase "*${TARGET_PART}*" $dev]} {
        set hw_device $dev
        break
    }
}

if {$hw_device eq ""} {
    puts "ERROR: No device matching '$TARGET_PART' found on JTAG chain."
    puts "ERROR: Devices present: $hw_devices"
    close_hw_target
    disconnect_hw_server
    close_hw_manager
    exit 1
}

puts "INFO: Targeting device: $hw_device"
current_hw_device $hw_device
refresh_hw_device -update_hw_probes false $hw_device

# ------------------------------------------------------------------------
# 4. Assign the bitstream and program the device
# ------------------------------------------------------------------------
set_property PROGRAM.FILE $BIT_FILE $hw_device

puts "INFO: Programming device with $BIT_FILE ..."
program_hw_devices $hw_device

# ------------------------------------------------------------------------
# 5. Verify programming succeeded
# ------------------------------------------------------------------------
refresh_hw_device $hw_device
set done_pin [get_property REGISTER.BIT0_STATUS.DONE $hw_device]
puts "INFO: DONE bit status: $done_pin"

# ------------------------------------------------------------------------
# 6. Clean up
# ------------------------------------------------------------------------
close_hw_target
disconnect_hw_server
close_hw_manager

puts "=================================================================="
puts "PROGRAMMING COMPLETE"
puts "Bitstream $BIT_FILE has been loaded onto $hw_device"
puts "Note: This is a volatile (SRAM) configuration - it will be lost on"
puts "power cycle. To program persistent flash/QSPI memory instead, use"
puts "Vivado's 'Add Configuration Memory Device' + program_hw_cfgmem flow."
puts "=================================================================="
